import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Electrical Calculator Methodology & Formulas",
  description:
    "Methodology, formulas, assumptions and source references for Green Engineering Tools voltage drop, wire size, cable length, current and power-loss calculators.",
  alternates: { canonical: "/electrical/methodology" },
};

export default function Page() {
  return (
    <main className="bg-white">
      <section className="bg-slate-950 text-white"><div className="mx-auto max-w-5xl px-4 py-14 sm:px-6 sm:py-18"><Link href="/electrical" className="text-xs font-black text-emerald-300 hover:underline">← Electrical tools</Link><h1 className="mt-5 text-4xl font-black sm:text-5xl">Electrical calculation methodology</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">The formulas, conductor properties, boundaries and responsible-use rules behind the electrical calculators.</p></div></section>
      <article className="mx-auto max-w-4xl space-y-12 px-4 py-14 sm:px-6 text-slate-600">
        <section><h2 className="text-3xl font-black text-slate-950">1. Current from power</h2><div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[640px] w-full text-sm"><thead className="bg-slate-950 text-white"><tr><th className="p-3 text-left">Circuit</th><th className="p-3 text-left">Active power</th><th className="p-3 text-left">Apparent power</th></tr></thead><tbody className="divide-y divide-slate-200"><tr><td className="p-3 font-bold">DC</td><td className="p-3">P = V × I</td><td className="p-3">Not separately modeled</td></tr><tr><td className="p-3 font-bold">Single-phase AC</td><td className="p-3">P = V × I × cos φ</td><td className="p-3">S = V × I</td></tr><tr><td className="p-3 font-bold">Balanced three-phase AC</td><td className="p-3">P = √3 × V × I × cos φ</td><td className="p-3">S = √3 × V × I</td></tr></tbody></table></div><p className="mt-4 leading-7">Three-phase voltage is line-to-line. The tool assumes a balanced load. Unbalanced phase and neutral-current studies are outside this engine.</p></section>

        <section><h2 className="text-3xl font-black text-slate-950">2. Conductor resistance versus temperature</h2><p className="mt-4 leading-7">When no manufacturer resistance is entered, the engine uses R = ρL/A with a linear temperature correction referenced to 20 °C. Reference values are 0.017241 Ω·mm²/m and α = 0.00393/°C for 100% IACS copper, and 0.028265 Ω·mm²/m and α = 0.00403/°C for 61% IACS conductor-grade aluminum. For real cable products, manufacturer resistance data is preferred because strand construction and product details can change actual resistance.</p></section>

        <section><h2 className="text-3xl font-black text-slate-950">3. Voltage drop</h2><div className="mt-4 rounded-2xl bg-slate-50 p-6 font-mono text-sm leading-7 text-slate-800"><p>DC: ΔU = 2 × I × L × R</p><p>Single-phase AC: ΔU = 2 × I × L × (R cosφ + X sinφ)</p><p>Balanced 3-phase AC: ΔU = √3 × I × L × (R cosφ + X sinφ)</p></div><p className="mt-4 leading-7">R and X are per-length cable values and are divided by the number of equal parallel conductors. Cable length is entered as the one-way source-to-load distance. Percentage drop is ΔU ÷ source voltage × 100.</p></section>

        <section><h2 className="text-3xl font-black text-slate-950">4. Real cable power loss</h2><p className="mt-4 leading-7">The tool uses conductor resistance, not reactance, for real power dissipation. DC and single-phase two-wire loss is 2 × I² × R × L; balanced three-phase loss is 3 × I² × R × L. Annual energy loss multiplies the operating loss by entered hours/day and 365 days. Annual cost is annual lost kWh × the user-entered energy tariff.</p></section>

        <section><h2 className="text-3xl font-black text-slate-950">5. Wire-size recommendation boundary</h2><p className="mt-4 leading-7">The automatic wire-size result searches the standard AWG/kcmil or metric catalog for the smallest size that meets the chosen voltage-drop target at the design current. It does not invent a worldwide ampacity table. Thermal ampacity depends on jurisdiction, cable insulation, installation method, grouping, ambient temperature, terminations and other corrections. If you already know the allowable ampacity of the selected cable after those checks, you can enter it manually in advanced inputs and the calculator will compare it with design current.</p></section>

        <section><h2 className="text-3xl font-black text-slate-950">6. Reference sources</h2><ul className="mt-5 space-y-4 text-sm leading-6"><li><a href="https://nvlpubs.nist.gov/nistpubs/Legacy/hb/nbshandbook100.pdf" target="_blank" rel="noopener noreferrer" className="font-black text-emerald-700 hover:underline">NIST / National Bureau of Standards — Copper Wire Tables</a><br/>Reference copper temperature coefficient and conductor-resistance background.</li><li><a href="https://nvlpubs.nist.gov/nistpubs/Legacy/circ/nbscircular346.pdf" target="_blank" rel="noopener noreferrer" className="font-black text-emerald-700 hover:underline">NIST / Bureau of Standards — Aluminum conductor properties</a><br/>Conductor-grade aluminum resistivity and temperature coefficient background.</li><li><a href="https://library.e.abb.com/public/561a28a17753c444c125714f00360967/1SDC010001D0204.pdf" target="_blank" rel="noopener noreferrer" className="font-black text-emerald-700 hover:underline">ABB — Electrical devices / cable dimensioning</a><br/>Single-phase and balanced three-phase voltage-drop relationship using R, X and power factor.</li><li><a href="https://www.se.com/us/en/download/document/0100DB2301/" target="_blank" rel="noopener noreferrer" className="font-black text-emerald-700 hover:underline">Schneider Electric — Electrical Distribution Fundamentals Design Guide</a><br/>Contemporary power-system design reference and reminder that simplified tools do not replace engineering practice.</li><li><a href="https://www.southwire.com/calculator-vdrop" target="_blank" rel="noopener noreferrer" className="font-black text-emerald-700 hover:underline">Southwire — Voltage Drop Calculator</a><br/>Industry comparison reference showing that conductor sizing must consider both voltage drop and ampacity.</li></ul></section>

        <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="text-2xl font-black text-amber-950">Not a code-compliance certificate</h2><p className="mt-3 text-sm leading-6 text-amber-900">Electrical codes and conductor ampacity rules vary by jurisdiction and installation. The calculator intentionally fails to claim universal compliance. Final circuit design should be reviewed against the current applicable standard, manufacturer instructions and local authority requirements by a qualified electrical professional.</p></section>
      </article>
    </main>
  );
}
