import React from 'react';

export default function TermsOfService() {
  return (
    <main className="max-w-4xl mx-auto px-6 py-12 text-gray-800">
      <h1 className="text-4xl font-bold text-green-700 mb-6">Terms of Service</h1>
      <p className="mb-4"><strong>Effective Date:</strong> August 29, 2026</p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">1. Acceptance of Terms</h2>
        <p className="mb-4">
          By accessing or using Green Engineering Tools (including the Embodied Carbon LCA and Smart Solar Load Calculator), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access our services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">2. Use of Our Tools</h2>
        <p className="mb-4">
          Our platforms are designed to provide engineering utility estimates. 
          The data and reports generated by the Embodied Carbon LCA and Solar Calculator are for informational and planning purposes only. 
          While we strive for accuracy using current EPD databases, we do not guarantee absolute precision. Final engineering decisions should always be reviewed by a certified professional.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">3. Intellectual Property</h2>
        <p className="mb-4">
          The SaaS applications, original content, features, and functionality are owned by Engr. Arsalan Khan and are protected by international copyright and intellectual property laws.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">4. Limitation of Liability</h2>
        <p className="mb-4">
          In no event shall Green Engineering Tools, nor its developers, be liable for any indirect, incidental, special, consequential or punitive damages resulting from your access to or use of, or inability to access or use the application.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">5. Governing Law</h2>
        <p className="mb-4">
          These Terms shall be governed and construed in accordance with the laws of Khyber Pakhtunkhwa, Pakistan, without regard to its conflict of law provisions.
        </p>
      </section>
    </main>
  );
}